[package]
name = "rust-minesweeper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clearscreen = "2.0.1"
colored = "2.0.0"
rand = "0.8.5"
termios = "0.3.3"
